name: vet_assist
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.1.0
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.3
  google_sign_in: ^6.3.0
  shared_preferences_android: ^2.4.10
  image_picker: ^1.1.2
  cloud_firestore: ^5.6.7
  firebase_storage: ^12.4.5
  intl: ^0.17.0
  provider: ^6.1.5
  google_maps_flutter: ^2.5.0
  geolocator: ^10.1.0
  http: ^1.1.0  # upgraded for flutter_svg compatibility
  fl_chart: ^1.0.0
  flutter_dotenv: ^5.1.0  # ✅ For loading Gemini API key

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - images/baluadiya.png
    - images/book.png
    - images/bot.png
    - images/location.png
    - images/pngwing.com (68).png
    - images/doggy and cat 1 (1).png
    - assest/icons/google.svg
    - assest/icons/fb.svg
    - api.env   # ✅ Add this to load Gemini API key
